### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",)) -> should be handled gracefully

### ISSUE THREAD

**Issue by okurz** [okurz/openqa_review#104]
## Observation

from cron email:

Subject: Cron <okurz@lord> env openqa_host=https://openqa.opensuse.org recv=okurz@suse.de html_target_file=openqa_opensuse_org_status.html TPL=$HOME/local/openqa_review/dashboard_files/dashboard.html.in $HOME/local/openqa_review/bin/openqa-review-daily-email; cp -a ~/{Export,public_html}/openqa_opensuse_org_status.html
Date: Sun,  5 Aug 2018 07:10:52 +0200 (CEST)

Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 9, in <module>
    load_entry_point('openqa-review==0.0.0', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1254, in main
    reminder_comment_on_issues(report)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1240, in reminder_comment_on_issues
    reminder_comment_on_issue(ie, min_days_unchanged)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1224, in reminder_comment_on_issue
    issue.add_comment(comment)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 660, in add_comment
    "is_private": True,
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 150, in json_rpc_post
    r = requests.post(absolute_url, data=data, auth=self.auth, headers={'content-type': 'application/json'})
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 471, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))

## Reproducible

Seen sometimes already

## Suggestions

104 should be handled gracefully.

**Comment by OleksandrOrlov** [comment]
Fixed by https://github.com/okurz/openqa_review/pull/107
