### ISSUE TITLE
Missing dependency: python-configparser is required

### ISSUE THREAD

**Issue by QingmingSu** [okurz/openqa_review#56]
The python-openqa_review package is installed by zypper command on my openSUSE Tumbleweed:

```
~> sudo zypper in python-openqa_review

~> openqa-review --help
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by openqa-review

After installing python-configparser:
~> sudo zypper in python-configparser
~> openqa-review --help
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 11, in <module>
    load_entry_point('openqa-review===.-0.0.0-', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2604, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2270, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 105, in <module>
    from configparser import ConfigParser, NoSectionError, NoOptionError  # isort:skip can not make isort happy here
  File "/usr/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named backports.configparser
```

The issue can be workaround by install configparser via pip
~> sudo pip install configparser
~> openqa-review --help
<works as expected>

**Comment by vpelcak** [comment]
Also packages python-pika and python-certifi are missing from dependencies for openSUSE.

**Comment by okurz** [comment]
fix is in https://build.opensuse.org/request/show/457127, waiting for accept

**Comment by okurz** [comment]
https://build.opensuse.org/request/show/458707 was replacement, accepted into Factory

**Comment by SergioAtSUSE** [comment]
It happens to me for Leap 42.2

```
mansilla@copland:/var/log/apache2$ openqa-review                                                                                                                                                                                      [58/58]
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by openqa-review
mansilla@copland:/var/log/apache2$
```
