### ISSUE TITLE
openqa-review in openSUSE Leap 42.2 script is not compatible with new openQA version

### ISSUE THREAD

**Issue by SergioAtSUSE** [okurz/openqa_review#63]
On openSUSE Leap 42.2, after installing openqa-review

```
zypper in python-openqa_review
zypper in python-configparser # because this dependency is not available yet (https://github.com/okurz/openqa_review/issues/56#issuecomment-300504567)
```

I get this error executing openqa_review

```
mansilla@copland:/var/log/apache2$ openqa-review                                                                                                                                                                                             
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 9, in <module>
    load_entry_point('openqa-review===.-0.0.0-', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1115, in main
    report = generate_report(args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1055, in generate_report
    return Report(browser, args, root_url, job_groups)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1008, in __init__
    self.report[k] = self._one_report(v)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1016, in _one_report
    return ProductReport(self.browser, job_group_url, self.root_url, self.args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 808, in __init__
    current_url, previous_url = get_build_urls_to_compare(browser, job_group_url, args.builds, args.against_reviewed, args.running_threshold)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 427, in get_build_urls_to_compare
    finished_builds = find_builds(get_group_result(job_group), running_threshold)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 378, in find_builds
    log.debug("Found the following finished non-empty builds: %s" % ', '.join(finished.keys()))
TypeError: sequence item 1: expected string or Unicode, NoneType found
mansilla@copland:/var/log/apache2$
```

**Comment by okurz** [comment]
I assume that is because of an incompatibility between openqa-review and a 
more recent openQA server. I recommend to crosscheck if that still happens as 
of today, if it also happens with another openQA server and crosscheck against 
the latest development version of openQA. Probably openSUSE Leap 42.2 would 
need an updated package which is not that easy due to most likely missing 
dependencies as you reported in the other issue already. We can try together 
some time as an exercise when you like :-)

**Comment by SergioAtSUSE** [comment]
1. still happens as of today

  ```
# openqa-review -vvvvv
DEBUG:openqa_review.openqa_review:Catched 'not enough builds': not enough finished builds found
INFO:openqa_review.openqa_review:Processing 'https://openqa.opensuse.org/group_overview/33'
DEBUG:openqa_review.openqa_review:Found the following finished non-empty builds: 
DEBUG:openqa_review.openqa_review:Catched 'not enough builds': not enough finished builds found
INFO:openqa_review.openqa_review:Processing 'https://openqa.opensuse.org/group_overview/7'
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 9, in <module>
    load_entry_point('openqa-review===.-0.0.0-', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1115, in main
    report = generate_report(args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1055, in generate_report
    return Report(browser, args, root_url, job_groups)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1008, in __init__
    self.report[k] = self._one_report(v)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1016, in _one_report
    return ProductReport(self.browser, job_group_url, self.root_url, self.args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 808, in __init__
    current_url, previous_url = get_build_urls_to_compare(browser, job_group_url, args.builds, args.against_reviewed, args.running_threshold)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 427, in get_build_urls_to_compare
    finished_builds = find_builds(get_group_result(job_group), running_threshold)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 378, in find_builds
    log.debug("Found the following finished non-empty builds: %s" % ', '.join(finished.keys()))
TypeError: sequence item 1: expected string or Unicode, NoneType found
```

2. works ok with --host https:://openqa.suse.de

**Comment by okurz** [comment]
New versions on openSUSE Leap:
* openSUSE Leap 42.3:    python-openqa_review-1.7.5-3.1
* openSUSE Leap 42.2:    python-openqa_review-1.7.5-5.6.1
