### ISSUE TITLE
retrieving bugs from bugzilla can fail and abort the script

### ISSUE THREAD

**Issue by okurz** [okurz/openqa_review#73]
## observation

```
Cron <okurz@lord> env TPL=/suse/okurz/Export/dashboard_files/dashboard.html.in $HOME/local/openqa_review/bin/openqa-review-daily-email
Date: Today 08:00:55
From: "(Cron Daemon)" <okurz@suse.de>
To: okurz@suse.de
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 9, in <module>
    load_entry_point('openqa-review==0.0.0', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1193, in main
    report = generate_report(args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1129, in generate_report
    return Report(browser, args, root_url, job_groups)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1079, in __init__
    self.report[k] = self._one_report(v)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1090, in _one_report
    return ProductReport(self.browser, job_group_url, self.root_url, self.args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 910, in __init__
    self.reports[arch] = ArchReport(arch, results, args, root_url, progress_browser, bugzilla_browser, browser)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 771, in __init__
    issue = Issue(bug['bugref'], bug['bugref_href'], self.args.query_issue_status, self.progress_browser, self.bugzilla_browser)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 609, in __init__
    self.json = bugzilla_browser.json_rpc_get('/jsonrpc.cgi', 'Bug.get', {"ids": [self.bugid]})['result']['bugs'][0]
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 129, in json_rpc_get
    return self.get_json(get_url.replace('http://dummy', ''), cache)
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 75, in get_json
    return self.get_page(url, as_json=True, cache=cache)
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 103, in get_page
    r = requests.get(absolute_url, auth=self.auth)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 471, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
```

## reproducible

seems to happen near every day now when the automatic report is generated. Seems to be more reproducible now as we have more bugs to retrieve data for

## problem

problems on retrieving single bugs should not abort the whole report generation

## suggestion

* handle one error gracefully, e.g. skip the retrieval of this one bug
* retry multiple times to retrieve one bug

**Comment by okurz** [comment]
Handled with version 1.8.0
