### ISSUE TITLE
Retry on 504

### ISSUE THREAD

**Issue by okurz** [okurz/openqa_review#78]
## Observation

```
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 9, in <module>
    load_entry_point('openqa-review==0.0.0', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1233, in main
    print(report)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1129, in __str__
    report_str += '# %s\n\n%s\n---\n' % (k, v)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 946, in __str__
    'arch_report': '\n---\n'.join(map(str, self.reports.values()))
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 881, in __str__
    'todo_issues': self._todo_issues_str(),
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 865, in _todo_issues_str
    'existing_issues': issue_listing('***existing issues***', self.issues['existing']['todo'], self.args.show_empty),
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 334, in issue_listing
    return '\n' + header + '\n\n' + ''.join(map(str, issues)) + '\n'
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 735, in __str__
    ', '.join(map(self._format_failure, self.failures)),
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 719, in _format_failure
    report_str = issue_report_link(self.root_url, f, self.test_browser) if (self.args.report_links and self.test_browser) else ''
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 488, in issue_report_link
    test_details_page = test_browser.get_soup(f['href'])
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 71, in get_soup
    return BeautifulSoup(self.get_page(url), "html.parser")
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 102, in get_page
    content = self._get(absolute_url, as_json=as_json)
  File "/usr/lib/python2.7/site-packages/openqa_review/browser.py", line 123, in _get
    raise DownloadError(msg)
openqa_review.browser.DownloadError: Request to https://openqa.opensuse.org/tests/654185 was not successful, status code: 504
```

## Expected result

openqa-review should not fail on this but skip or retry gracefully

**Comment by OleksandrOrlov** [comment]
Added PR: https://github.com/okurz/openqa_review/pull/88

Could you please review.

**Comment by okurz** [comment]
Fixed with https://github.com/okurz/openqa_review/pull/88 , thx
