### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__' in get_test_details

### ISSUE THREAD

**Issue by okurz** [okurz/openqa_review#79]
## Observation

```python
Traceback (most recent call last):
  File "/usr/bin/openqa-review", line 9, in <module>
    load_entry_point('openqa-review==0.0.0', 'console_scripts', 'openqa-review')()
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1220, in main
    report = generate_report(args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1156, in generate_report
    return Report(browser, args, root_url, job_groups)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1106, in __init__
    self.report[k] = self._one_report(v)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 1117, in _one_report
    return ProductReport(self.browser, job_group_url, self.root_url, self.args)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 928, in __init__
    results = get_arch_state_results(arch, current_details, previous_details, args.output_state_results)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 288, in get_arch_state_results
    states = SortedDict(get_state(v, test_results_previous_dict) for k, v in iteritems(test_results_dict))
  File "/usr/lib/python2.7/site-packages/sortedcontainers/sorteddict.py", line 140, in __init__
    self._update(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/sortedcontainers/sorteddict.py", line 338, in update
    self._dict_update(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 288, in <genexpr>
    states = SortedDict(get_state(v, test_results_previous_dict) for k, v in iteritems(test_results_dict))
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 276, in get_state
    state_dict.update(get_test_details(cur))
  File "/usr/lib/python2.7/site-packages/openqa_review/openqa_review.py", line 250, in get_test_details
    'failedmodules': [{'href': m.a['href'], 'name': m.text.strip(), 'needles': get_failed_needles(m)} for m in failedmodules]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by okurz** [comment]
this seems to happen now on o3 and osd since the most recent deployment so probably the API changed. I guess @Martchus knows more here :)

**Comment by okurz** [comment]
Fixed with https://github.com/okurz/openqa_review/pull/80

Thank you @nicksinger
